# Example netlify.toml for a Next.js App Router project
[build]
  command = "next build"
  publish = ".next" # Standard output directory for Next.js

# Redirects and rewrites for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[plugins]
  # Essential plugin for Next.js on Netlify
  [[plugins.package]]
    package = "@netlify/plugin-nextjs"
